/* tslint:disable */
/* eslint-disable */
/**
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-node).
 * https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-node
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

export const BASE_PATH = "".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface RequestArgs
 */
export interface RequestArgs {
    url: string;
    options: RawAxiosRequestConfig;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath ?? basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    constructor(public field: string, msg?: string) {
        super(msg);
        this.name = "RequiredError"
    }
}

/**
 * API exception carrying HTTP status, headers, raw body, and parsed business error fields.
 * @export
 * @class ApiException
 * @extends {Error}
 */
export class ApiException extends Error {
    public readonly httpStatus: number;
    public readonly responseHeaders: Record<string, string> | undefined;
    public readonly responseBody: string | undefined;

    public readonly errorCode: number;
    public readonly errorMessage: string | undefined;
    public readonly innerError: Error | undefined;

    constructor(
        message: string,
        httpStatus: number = 0,
        responseHeaders?: Record<string, string>,
        responseBody?: string,
        cause?: Error,
    ) {
        super(message);
        this.innerError = cause;
        this.name = 'ApiException';
        this.httpStatus = httpStatus;
        this.responseHeaders = responseHeaders;
        this.responseBody = responseBody;

        const parsed = ApiException._parseBody(responseBody);
        this.errorCode = parsed.code;
        this.errorMessage = parsed.msg;

        Object.setPrototypeOf(this, new.target.prototype);
    }

    override toString(): string {
        return `${this.name}: HTTP ${this.httpStatus} – ${this.message}` +
            (this.responseBody ? `\nResponse body: ${this.responseBody}` : '');
    }

    static fromResponse(
        message: string,
        httpStatus: number,
        headers?: Record<string, string>,
        body?: string,
        cause?: Error,
    ): ApiException {
        switch (httpStatus) {
            case 400:
                return new BadRequestException(message, httpStatus, headers, body, cause);
            case 401:
                return new UnauthorizedException(message, httpStatus, headers, body, cause);
            case 403:
                return new ForbiddenException(message, httpStatus, headers, body, cause);
            case 404:
                return new NotFoundException(message, httpStatus, headers, body, cause);
            case 409:
                return new ConflictException(message, httpStatus, headers, body, cause);
            case 422:
                return new UnprocessableEntityException(message, httpStatus, headers, body, cause);
            case 429:
                return new TooManyRequestsException(message, httpStatus, headers, body, cause);
            default:
                if (httpStatus >= 500) {
                    return new ServiceException(message, httpStatus, headers, body, cause);
                }
                return new ApiException(message, httpStatus, headers, body, cause);
        }
    }

    static fromNetworkError(cause: Error): NetworkException {
        return new NetworkException(cause.message, cause);
    }

    private static _parseBody(body: string | undefined): { code: number; msg: string | undefined } {
        if (!body) return { code: -1, msg: undefined };
        try {
            const obj = JSON.parse(body);
            if (typeof obj !== 'object' || obj === null) return { code: -1, msg: undefined };
            const code = typeof obj.code === 'number' ? obj.code : -1;
            const msg = typeof obj.errorMessage === 'string' ? obj.errorMessage : undefined;
            return { code, msg };
        } catch {
            return { code: -1, msg: undefined };
        }
    }
}

/** HTTP 400 Bad Request. */
export class BadRequestException extends ApiException {
    constructor(message: string, httpStatus: number, headers?: Record<string, string>, body?: string, cause?: Error) {
        super(message, httpStatus, headers, body, cause);
        this.name = 'BadRequestException';
    }
}

/** HTTP 401 Unauthorized. */
export class UnauthorizedException extends ApiException {
    constructor(message: string, httpStatus: number, headers?: Record<string, string>, body?: string, cause?: Error) {
        super(message, httpStatus, headers, body, cause);
        this.name = 'UnauthorizedException';
    }
}

/** HTTP 403 Forbidden. */
export class ForbiddenException extends ApiException {
    constructor(message: string, httpStatus: number, headers?: Record<string, string>, body?: string, cause?: Error) {
        super(message, httpStatus, headers, body, cause);
        this.name = 'ForbiddenException';
    }
}

/** HTTP 404 Not Found. */
export class NotFoundException extends ApiException {
    constructor(message: string, httpStatus: number, headers?: Record<string, string>, body?: string, cause?: Error) {
        super(message, httpStatus, headers, body, cause);
        this.name = 'NotFoundException';
    }
}

/** HTTP 409 Conflict — e.g. resource already exists. */
export class ConflictException extends ApiException {
    constructor(message: string, httpStatus: number, headers?: Record<string, string>, body?: string, cause?: Error) {
        super(message, httpStatus, headers, body, cause);
        this.name = 'ConflictException';
    }
}

/** HTTP 422 Unprocessable Entity. */
export class UnprocessableEntityException extends ApiException {
    constructor(message: string, httpStatus: number, headers?: Record<string, string>, body?: string, cause?: Error) {
        super(message, httpStatus, headers, body, cause);
        this.name = 'UnprocessableEntityException';
    }
}

/** HTTP 429 Too Many Requests — rate limited. */
export class TooManyRequestsException extends ApiException {
    constructor(message: string, httpStatus: number, headers?: Record<string, string>, body?: string, cause?: Error) {
        super(message, httpStatus, headers, body, cause);
        this.name = 'TooManyRequestsException';
    }
}

/** HTTP 5xx Server Error. */
export class ServiceException extends ApiException {
    constructor(message: string, httpStatus: number, headers?: Record<string, string>, body?: string, cause?: Error) {
        super(message, httpStatus, headers, body, cause);
        this.name = 'ServiceException';
    }
}

/** Network-level error (no HTTP response received). */
export class NetworkException extends ApiException {
    constructor(message: string, cause?: Error) {
        super(message, 0, undefined, undefined, cause);
        this.name = 'NetworkException';
    }
}

interface ServerMap {
    [key: string]: {
        url: string,
        description: string,
    }[];
}

/**
 *
 * @export
 */
export const operationServerMap: ServerMap = {
}
