/* tslint:disable */
/* eslint-disable */
/**
 * Nexconn Server API
 * OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: customercare@nexconn.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-node).
 * https://gitlab2.rongcloud.net/public-server/nexconn-server-sdk-node
 * Do not edit the class manually.
 */


import { createHash, randomBytes } from 'crypto';

export interface ServerEntry {
    url: string;
    description: string;
}

export interface ConfigurationParameters {
    apiKey?: string | Promise<string> | ((name: string) => string) | ((name: string) => Promise<string>);
    username?: string;
    password?: string;
    accessToken?: string | Promise<string> | ((name?: string, scopes?: string[]) => string) | ((name?: string, scopes?: string[]) => Promise<string>);
    basePath?: string;
    serverIndex?: number;
    baseOptions?: any;
    formDataCtor?: new () => any;
}

export class Configuration {
    /**
     * parameter for apiKey security
     * @param name security name
     * @memberof Configuration
     */
    apiKey?: string | Promise<string> | ((name: string) => string) | ((name: string) => Promise<string>);
    /**
     * parameter for basic security
     *
     * @type {string}
     * @memberof Configuration
     */
    username?: string;
    /**
     * parameter for basic security
     *
     * @type {string}
     * @memberof Configuration
     */
    password?: string;
    /**
     * parameter for oauth2 security
     * @param name security name
     * @param scopes oauth2 scope
     * @memberof Configuration
     */
    accessToken?: string | Promise<string> | ((name?: string, scopes?: string[]) => string) | ((name?: string, scopes?: string[]) => Promise<string>);
    /**
     * override base path
     *
     * @type {string}
     * @memberof Configuration
     */
    basePath?: string;
    /**
     * override server index
     *
     * @type {number}
     * @memberof Configuration
     */
    serverIndex?: number;
    /**
     * base options for axios calls
     *
     * @type {any}
     * @memberof Configuration
     */
    baseOptions?: any;
    /**
     * The FormData constructor that will be used to create multipart form data
     * requests. You can inject this here so that execution environments that
     * do not support the FormData class can still run the generated client.
     *
     * @type {new () => FormData}
     */
    formDataCtor?: new () => any;

    private _appSecret: string = '';
    private _nonceGenerator: () => string;
    private _autoFailoverEnabled: boolean = true;
    private _errorSwitchingThreshold: number = 1;
    private _errorCounter: number = 0;
    private _domainIndex: number = 0;
    private _customServers: ServerEntry[] = [];

    constructor(param: ConfigurationParameters = {}) {
        this.apiKey = param.apiKey;
        this.username = param.username;
        this.password = param.password;
        this.accessToken = param.accessToken;
        this.basePath = param.basePath;
        this.serverIndex = param.serverIndex;
        this.baseOptions = {
            ...param.baseOptions,
            headers: {
                'User-Agent': "nexconn-sdk-node/0.1.0",
                ...param.baseOptions?.headers,
            },
        };
        this.formDataCtor = param.formDataCtor;
        this._nonceGenerator = Configuration._defaultNonceGenerator;
    }

    /**
     * Set Nexconn credentials for automatic request signing.
     * The SDK injects App-Key / Nonce / Timestamp / Signature headers.
     */
    public setNexconnCredentials(appKey: string, appSecret: string): this {
        this.apiKey = appKey;
        this._appSecret = appSecret;
        return this;
    }

    /**
     * Configure primary and backup API domains.
     * The SDK does not embed any default domain; this must be called before
     * sending requests.
     */
    public setPrimaryBackupDomains(primaryUrl: string, backupUrl: string): this {
        return this.setServers([
            { url: primaryUrl, description: 'Primary domain' },
            { url: backupUrl, description: 'Backup domain' },
        ]);
    }

    /**
     * Configure multiple API domains for failover.
     * At least two servers (primary + backup) are required.
     */
    public setServers(servers: ServerEntry[]): this {
        if (servers.length < 2) {
            throw new Error('servers must contain both primary and backup domains');
        }
        this._customServers = servers.map(s => ({
            url: s.url.replace(/\/+$/, ''),
            description: s.description || '',
        }));
        this.basePath = undefined;
        this.serverIndex = 0;
        this._errorCounter = 0;
        this._domainIndex = 0;
        return this;
    }

    /**
     * Set how many consecutive failures trigger a domain switch.
     * Default is 1 (switch on next request after a single failure).
     */
    public setErrorSwitchingThreshold(threshold: number): this {
        this._errorSwitchingThreshold = Math.max(1, Math.floor(threshold));
        return this;
    }

    /**
     * Enable or disable automatic domain failover.
     * When disabled, requests always use the server at `serverIndex`.
     */
    public setAutoFailoverEnabled(enabled: boolean): this {
        this._autoFailoverEnabled = enabled;
        return this;
    }

    /**
     * Override the default nonce generator.
     * The returned string is sent as the `Nonce` request header.
     */
    public setNonceGenerator(generator: () => string): this {
        this._nonceGenerator = generator;
        return this;
    }

    /**
     * Record a domain failure (HTTP 5xx or network error).
     * Called internally by the SDK; not intended for direct use.
     */
    public markDomainFailure(): void {
        if (this._autoFailoverEnabled && this._customServers.length > 0) {
            this._errorCounter++;
        }
    }

    /**
     * Return the currently active API host URL, applying failover logic
     * when custom servers are configured.
     */
    public getActiveHost(): string {
        if (this._customServers.length > 0) {
            if (this._autoFailoverEnabled) {
                const idx = this._getFailoverServerIndex(this._customServers.length);
                return this._customServers[idx].url;
            }
            return this._customServers[this.serverIndex ?? 0].url;
        }

        if (this.basePath) {
            return this.basePath;
        }

        throw new Error(
            'No API domains configured. Call configuration.setPrimaryBackupDomains() ' +
            'or configuration.setServers() before sending requests.'
        );
    }

    /**
     * Inject Nexconn signing headers into a request header map.
     * Adds X-Request-ID unconditionally; adds Nonce / Timestamp / Signature
     * only when App-Key is present (i.e. credentials have been configured).
     */
    public applySigningHeaders(headers: Record<string, any>): void {
        if (!headers['X-Request-ID']) {
            headers['X-Request-ID'] = Configuration._generateUUID();
        }

        const appKey = headers['App-Key'];
        if (!appKey) return;

        if (!headers['Nonce'] && this._nonceGenerator) {
            const nonce = this._nonceGenerator();
            if (nonce) {
                headers['Nonce'] = String(nonce);
            }
        }

        if (!headers['Timestamp']) {
            headers['Timestamp'] = String(Date.now());
        }

        if (this._appSecret && headers['Nonce']) {
            const payload = this._appSecret + headers['Nonce'] + headers['Timestamp'];
            headers['Signature'] = createHash('sha1').update(payload, 'utf8').digest('hex');
        }
    }

    /**
     * Check if the given MIME is a JSON MIME.
     * JSON MIME examples:
     *   application/json
     *   application/json; charset=UTF8
     *   APPLICATION/JSON
     *   application/vnd.company+json
     * @param mime - MIME (Multipurpose Internet Mail Extensions)
     * @return True if the given MIME is JSON, false otherwise.
     */
    public isJsonMime(mime: string): boolean {
        const jsonMime: RegExp = new RegExp('^(application\/json|[^;/ \t]+\/[^;/ \t]+[+]json)[ \t]*(;.*)?$', 'i');
        return mime !== null && (jsonMime.test(mime) || mime.toLowerCase() === 'application/json-patch+json');
    }

    private _getFailoverServerIndex(serverCount: number): number {
        if (serverCount <= 0) return 0;
        if (this._errorCounter >= this._errorSwitchingThreshold) {
            this._errorCounter = 0;
            this._domainIndex++;
        }
        return Math.abs(this._domainIndex) % serverCount;
    }

    private static _defaultNonceGenerator(): string {
        const buf = randomBytes(8);
        let n = 0;
        for (let i = 0; i < 7; i++) {
            n = n * 256 + buf[i];
        }
        return String(n);
    }

    private static _generateUUID(): string {
        const bytes = randomBytes(16);
        bytes[6] = (bytes[6] & 0x0f) | 0x40;
        bytes[8] = (bytes[8] & 0x3f) | 0x80;
        const hex = bytes.toString('hex');
        return [
            hex.slice(0, 8),
            hex.slice(8, 12),
            hex.slice(12, 16),
            hex.slice(16, 20),
            hex.slice(20, 32),
        ].join('-');
    }
}
